stages:
  - deploy to dev
  - deploy to prod

variables:
  APP_NAME: "payform-widget"
  DEV_HOST: "admin@84.201.139.43"
  DEV_RELEASE_ROOT: "/home/admin/web/widget.dev.prodamus.ru/${CI_ENVIRONMENT_NAME}"
  PROD_HOST: "prodamus@81.163.20.106"
  PROD_RELEASE_ROOT: "/var/www/widget.prodamus.ru/${CI_ENVIRONMENT_NAME}"

deploy to dev:
  stage: deploy to dev
  variables:
    TARGET_HOST: "${DEV_HOST}"
  script:
    - |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      npm i && npm run build -- --mode development --env development
      ls -al dist/
    - RELEASES_DIR="${DEV_RELEASE_ROOT}/releases"
    - CURRENT_RELEASE="$RELEASES_DIR/$(date +%F-%s)"
    - echo $CURRENT_RELEASE
    - ssh "$TARGET_HOST" "mkdir -p $CURRENT_RELEASE"
    - rsync -av dist/ "$TARGET_HOST:$CURRENT_RELEASE/"
    - rsync -av /home/gitlab-runner/builds/E-xSye_Y/0/prodamus/payform-widget/public/src/ "$TARGET_HOST:$CURRENT_RELEASE/src/"
    - ssh "$TARGET_HOST" "ln -sfn $CURRENT_RELEASE $DEV_RELEASE_ROOT/current"
    - echo Check out deployment url $CI_ENVIRONMENT_URL
  environment:
    name: dev
    url: "https://widget.dev.prodamus.ru"
  when: manual
  tags:
    - gibus4

deploy to prod:
  stage: deploy to prod
  variables:
    TARGET_HOST: "${PROD_HOST}"
  script:
    - |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      npm i && npm run build -- --mode production --env production
      ls -al dist/
    - RELEASES_DIR="${PROD_RELEASE_ROOT}/releases"
    - CURRENT_RELEASE="$RELEASES_DIR/$(date +%F-%s)"
    - echo $CURRENT_RELEASE
    - ssh "$TARGET_HOST" "mkdir -p $CURRENT_RELEASE"
    - rsync -av dist/ "$TARGET_HOST:$CURRENT_RELEASE/"
    - rsync -av /home/gitlab-runner/builds/E-xSye_Y/0/prodamus/payform-widget/public/src/ "$TARGET_HOST:$CURRENT_RELEASE/src/"
    - ssh "$TARGET_HOST" "ln -sfn $CURRENT_RELEASE $PROD_RELEASE_ROOT/current"
    - echo Check out deployment url $CI_ENVIRONMENT_URL
  environment:
    name: prod
    url: "https://widget.prodamus.ru"
  only:
    - master
    - /^v[\d\.]+$/
  when: manual
  tags:
    - gibus4
